### ISSUE TITLE
AttributeError: 'module' object has no attribute 'path'

### ISSUE THREAD

**Issue by eyildiz-ugoe** [dimatura/seeing3d#4]
Full error message:

```
user@user:~/workspace/seeing3d$ python render.py ~/ownCloud/3D\ Models/Tools/hammer/ renderedmodels/
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
Traceback (most recent call last):
  File "render.py", line 211, in <module>
    main()
  File "render.py", line 175, in main
    load_model()
  File "render.py", line 99, in load_model
    model_dir = path.path(args.MODEL_DIR)
AttributeError: 'module' object has no attribute 'path'
python: built-cp27-cp27mu/include/mutexPosixImpl.I:54: void MutexPosixImpl::acquire(): Assertion `result == 0' failed.
Aborted (core dumped)

```

OS: Ubuntu 16.04 64bit
Python: 2.7

What kind of input should we provide to get the renderer to do the magic? I referred the folder of collada models as well as .obj but no luck.

**Comment by Howardyangyixuan** [comment]
change to "path.Path()"  instead
